// frontend/dashboard-ui/src/components/AlphaDemo.jsx
import React, { useState, useEffect } from 'react';

const AlphaDemo = () => {
  const [symbol, setSymbol] = useState('IBM');
  const [snapshot, setSnapshot] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const fetchDemo = async () => {
    setLoading(true);
    setError(null);
    setSnapshot(null);
    try {
      const res = await fetch(`/api/alpha-demo?symbol=${encodeURIComponent(symbol)}`);
      if (!res.ok) {
        setError(`Server error (${res.status}): ${await res.text()}`);
      } else {
        setSnapshot(await res.json());
      }
    } catch (e) {
      setError(e.message || 'Network error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDemo();
  }, []); // Run once on mount

  const formattedSnapshot = () => {
    if (!snapshot) return '';
    try {
      return JSON.stringify(snapshot, null, 2);
    } catch (e) {
      return String(snapshot);
    }
  };

  return (
    <div className="alpha-demo">
      <h2>Alpha Vantage Demo</h2>
      <div>
        <input
          type="text"
          value={symbol}
          onChange={(e) => setSymbol(e.target.value)}
          placeholder="Symbol (e.g., IBM, NIFTY)"
        />
        <button onClick={fetchDemo}>Fetch</button>
      </div>

      {loading && <div>Loading…</div>}

      {error && <div className="error">{error}</div>}

      {snapshot && <pre>{formattedSnapshot()}</pre>}
    </div>
  );
};

export default AlphaDemo;

// frontend/src/components/AlphaDemo.vue
<template>
  <div class="alpha-demo">
    <h2>Alpha Vantage Demo</h2>
    <div>
      <input v-model="symbol" placeholder="Symbol (e.g., IBM, NIFTY)" />
      <button @click="fetchDemo">Fetch</button>
    </div>

    <div v-if="loading">Loading…</div>

    <div v-if="error" class="error">{{ error }}</div>

    <pre v-if="snapshot">{{ formattedSnapshot }}</pre>
  </div>
</template>

<script>
export default {
  name: 'AlphaDemo',
  data() {
    return {
      symbol: 'IBM',
      snapshot: null,
      loading: false,
      error: null,
    }
  },
  computed: {
    formattedSnapshot() {
      if (!this.snapshot) return '';
      try {
        return JSON.stringify(this.snapshot, null, 2);
      } catch (e) {
        return String(this.snapshot);
      }
    }
  },
  methods: {
    async fetchDemo() {
      this.loading = true;
      this.error = null;
      this.snapshot = null;
      try {
        const res = await fetch(`/api/alpha-demo?symbol=${encodeURIComponent(this.symbol)}`);
        if (!res.ok) {
          this.error = `Server error (${res.status}): ${await res.text()}`;
        } else {
          this.snapshot = await res.json();
        }
      } catch (e) {
        this.error = e.message || 'Network error';
      } finally {
        this.loading = false;
      }
    }
  },
  mounted() {
    // Auto-fetch once for convenience
    this.fetchDemo();
  }
}
</script>

<style scoped>
.alpha-demo { padding: 1rem; border: 1px solid #ddd; border-radius: 6px; }
.error { color: red; margin-top: 0.5rem; }
pre { background: #f7f7f7; padding: 0.75rem; border-radius: 4px; }
</style>
